app:
  image: "jigneshpt/blogger:${IMAGE_TAG}"
  links:
   - db:db
  ports:
   - 9999:8080

db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /var/lib/mysql
